# Text File
# AUTHOR:   manawasp
# MAIL:     clovis.kyndt@gmail.com
# FILE:     Gemfile
# ROLE:     TODO (some explanation)
# CREATED:  2014-07-02 15:59:53
# MODIFIED: 2015-04-11 22:21:19

source 'https://rubygems.org'
ruby "2.1.1"
gem 'rails', '4.1.1'
gem 'compass', '~> 0.13.alpha.4'
gem 'compass-rails', '~> 1.0.3'
gem 'haml', '~> 4.0.3'
gem 'haml-rails'
gem 'coffee-script'
gem 'guard'
gem 'guard-haml'
gem 'guard-coffeescript'
gem 'guard-compass'
gem 'middleman'
