// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Cv': typeof import("../components/Cv.vue")['default'],
    'Education': typeof import("../components/Education.vue")['default'],
    'Extra': typeof import("../components/Extra.vue")['default'],
    'Footer': typeof import("../components/Footer.vue")['default'],
    'Header': typeof import("../components/Header.vue")['default'],
    'Introduction': typeof import("../components/Introduction.vue")['default'],
    'Knowledge': typeof import("../components/Knowledge.vue")['default'],
    'Language': typeof import("../components/Language.vue")['default'],
    'Project': typeof import("../components/Project.vue")['default'],
    'Work': typeof import("../components/Work.vue")['default'],
    '': typeof import("../components/index.ts")['default'],
    'NuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.1/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyCv': typeof import("../components/Cv.vue")['default'],
    'LazyEducation': typeof import("../components/Education.vue")['default'],
    'LazyExtra': typeof import("../components/Extra.vue")['default'],
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyHeader': typeof import("../components/Header.vue")['default'],
    'LazyIntroduction': typeof import("../components/Introduction.vue")['default'],
    'LazyKnowledge': typeof import("../components/Knowledge.vue")['default'],
    'LazyLanguage': typeof import("../components/Language.vue")['default'],
    'LazyProject': typeof import("../components/Project.vue")['default'],
    'LazyWork': typeof import("../components/Work.vue")['default'],
    'Lazy': typeof import("../components/index.ts")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.1/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const Cv: typeof import("../components/Cv.vue")['default']
export const Education: typeof import("../components/Education.vue")['default']
export const Extra: typeof import("../components/Extra.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Introduction: typeof import("../components/Introduction.vue")['default']
export const Knowledge: typeof import("../components/Knowledge.vue")['default']
export const Language: typeof import("../components/Language.vue")['default']
export const Project: typeof import("../components/Project.vue")['default']
export const Work: typeof import("../components/Work.vue")['default']
export const : typeof import("../components/index.ts")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.1/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyCv: typeof import("../components/Cv.vue")['default']
export const LazyEducation: typeof import("../components/Education.vue")['default']
export const LazyExtra: typeof import("../components/Extra.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyIntroduction: typeof import("../components/Introduction.vue")['default']
export const LazyKnowledge: typeof import("../components/Knowledge.vue")['default']
export const LazyLanguage: typeof import("../components/Language.vue")['default']
export const LazyProject: typeof import("../components/Project.vue")['default']
export const LazyWork: typeof import("../components/Work.vue")['default']
export const Lazy: typeof import("../components/index.ts")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.1/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.5_sass@1.53.0+webpack@5.73.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
