// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Block': typeof import("../components/Block.vue")['default'],
    'Footer': typeof import("../components/Footer.vue")['default'],
    'Header': typeof import("../components/Header.vue")['default'],
    'Table': typeof import("../components/Table.vue")['default'],
    'Text': typeof import("../components/Text.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyBlock': typeof import("../components/Block.vue")['default'],
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyHeader': typeof import("../components/Header.vue")['default'],
    'LazyTable': typeof import("../components/Table.vue")['default'],
    'LazyText': typeof import("../components/Text.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const Block: typeof import("../components/Block.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Table: typeof import("../components/Table.vue")['default']
export const Text: typeof import("../components/Text.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyBlock: typeof import("../components/Block.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyTable: typeof import("../components/Table.vue")['default']
export const LazyText: typeof import("../components/Text.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.2.2/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.6_sass@1.54.4+webpack@5.74.0/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
